acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }
acme_alumnos:
    pattern:  /alumnos
    defaults: { _controller: AcmeHelloBundle:Default:alumnos }