proyectoinicio_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: proyectoinicioBundle:Default:index }
proyectoinicio_reapaso:
    pattern:  /repaso
    defaults: { _controller: proyectoinicioBundle:Default:repaso }

proyectoinicio_reapaso2:
    pattern:  /repaso2
    defaults: { _controller: proyectoinicioBundle:Default:repaso2 }
