parameters:
#    proyectoinicio.example.class: proyecto\inicioBundle\Example

services:
#    proyectoinicio.example:
#        class: %proyectoinicio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
